### ISSUE TITLE
Completely borked

### ISSUE THREAD

**Issue by kvnspncr** [infamouskoala/Win-token-logger#1]
This is completely borked and never ever worked, if you aren't 12 years old and can read code you will notice that this doesn't even have a function to dump the leveldb extracted from Discord. Not only that but it doesn't even extract the DB properly.

I suggest purging this repo until someone other than 12 year old kids in your server sees this.

Best of luck, 
Kevin

**Comment by infamouskoala** [comment]
Kevin my beloved, why are u so obsessed w me? Just because people don't value ur work as good as they value mine
doesn't mean ur gonna be all bumhurt and start falsely accusing my shit of being "borked" 😂 also the amount of racism you got against indians is insane. Did ur mum cheat on ur dad with some indian? cuz i see no reason why ur so racist towards us.
Some people are just good and u gotta accept it instead of being bumhurt and trying to leave nagative comments on their stuff 😂 
Also its bizzaire how u claim to be a malware dev and u still dont know u can have custom modified iso for windows (the one im using) or how u can block trackers with like a 10 line batch code (that i did aswell)
So yeah u are simply bumhurt because of the clout that i (a stupid indian) have and u couldn't have.
Either way, have a good day
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/353f5377-a053-469c-8d5b-0b5a78c8cb4f)
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/43cc83e9-86d2-43cd-a177-36ab0e722cfc)
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/088b2d22-a1e8-4468-b542-005dc305cb79)
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/2e4ea6a7-156b-4f75-ba85-60371ad67770)
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/4319a8f1-37cb-4dfc-830a-eea0e596d5a0)
![image](https://github.com/infamouskoala/Win-token-logger/assets/75808182/f3c0cec4-b914-4679-8ed3-80db9ed2bd23)

**Comment by benilyasss** [comment]
> Kevin my beloved, why are u so obsessed w me? Just because people don't value ur work as good as they value mine doesn't mean ur gonna be all bumhurt and start falsely accusing my shit of being "borked" 😂 also the amount of racism you got against indians is insane. Did ur mum cheat on ur dad with some indian? cuz i see no reason why ur so racist towards us. Some people are just good and u gotta accept it instead of being bumhurt and trying to leave nagative comments on their stuff 😂 Also its bizzaire how u claim to be a malware dev and u still dont know u can have custom modified iso for windows (the one im using) or how u can block trackers with like a 10 line batch code (that i did aswell) So yeah u are simply bumhurt because of the clout that i (a stupid indian) have and u couldn't have. Either way, have a good day ![image](https://private-user-images.githubusercontent.com/75808182/294695780-353f5377-a053-469c-8d5b-0b5a78c8cb4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU3ODAtMzUzZjUzNzctYTA1My00NjljLThkNWItMGI1YTc4YzhjYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyN2JlNDM1NTI0MDhmOWY0ZjY3ZjQyOTMyOGZhNjAyYmUxZDFjMThmYzdkOGUxZTJlMDQzZmFjMTY4ODVhNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WW6pNKovf5e-zLOdTpw1Rp4vcyzNyhRRlSLWBw8GH_k) ![image](https://private-user-images.githubusercontent.com/75808182/294695782-43cc83e9-86d2-43cd-a177-36ab0e722cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU3ODItNDNjYzgzZTktODZkMi00M2NkLWExNzctMzZhYjBlNzIyY2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyY2Y1YmZlZmU5Nzc0NzMzZmQ1NTIyZjc0N2I0MTNjYjk0NzdlODQ2YTJiNTU1YTZhNzUxMmNiNjBhYTdjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IsS0-wMgcXd4RxY_bV-Xf2SxAe1FrQ37FdjFUDeH0vo) ![image](https://private-user-images.githubusercontent.com/75808182/294695802-088b2d22-a1e8-4468-b542-005dc305cb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU4MDItMDg4YjJkMjItYTFlOC00NDY4LWI1NDItMDA1ZGMzMDVjYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MTc0NWNjNDA4M2U3NTE4NzQ1YzY0MTlhODQ5NjA1MjE1ODllZTNiMmQ1ZWNhNjI3MTA1NjczNTg4MmI5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FCUkoT3hhw-c0KjQGPOS1JeCb-bUtWW9QlXDVfzxX-U) ![image](https://private-user-images.githubusercontent.com/75808182/294695917-2e4ea6a7-156b-4f75-ba85-60371ad67770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU5MTctMmU0ZWE2YTctMTU2Yi00Zjc1LWJhODUtNjAzNzFhZDY3NzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NDYwZjIxNzM3NDdkOTZiN2Q2YjMzZDkzZDNiODk3MzE5MWViYzY5M2EzNjVlMDIzMDFiYWNlOTliZjVkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUEswbEx87NDZfKAyCBXK8bl6i4wYHIUgYpXVStCDL8) ![image](https://private-user-images.githubusercontent.com/75808182/294695940-4319a8f1-37cb-4dfc-830a-eea0e596d5a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU5NDAtNDMxOWE4ZjEtMzdjYi00ZGZjLTgzMGEtZWVhMGU1OTZkNWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYzgwOWVkNDRmZDE1ZjFiMTRiYjMzMjAyMTMyNDUzMDFjYzBhZTI4NWFhMTUwZTgwNzAyN2ZmODViNWExOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.929FSBvF7U7JlyIaoI0du6Vu45KA6h63TzrfIfCPZW0) ![image](https://private-user-images.githubusercontent.com/75808182/294696043-f3c0cec4-b914-4679-8ed3-80db9ed2bd23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTEzOTQsIm5iZiI6MTcwNDU1MTA5NCwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTYwNDMtZjNjMGNlYzQtYjkxNC00Njc5LThlZDMtODBkYjllZDJiZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzUwOTBiMjlmMzcxOGRlNjc5YjA3Y2EwOTViYTE4NTE5MWU2Nzc1OWM1YmVlYTg1OWZkYjNlMjMwYjc4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tkpIY-3uMswiPopNxWjYNQkDvubeicBADc3HOUDLvtc)

giv me perms in ur sw xdxdxdxddxdxdxdxdxd

**Comment by kvnspncr** [comment]
> Kevin my beloved, why are u so obsessed w me? Just because people don't value ur work as good as they value mine doesn't mean ur gonna be all bumhurt and start falsely accusing my shit of being "borked" 😂 also the amount of racism you got against indians is insane. Did ur mum cheat on ur dad with some indian? cuz i see no reason why ur so racist towards us. Some people are just good and u gotta accept it instead of being bumhurt and trying to leave nagative comments on their stuff 😂 Also its bizzaire how u claim to be a malware dev and u still dont know u can have custom modified iso for windows (the one im using) or how u can block trackers with like a 10 line batch code (that i did aswell) So yeah u are simply bumhurt because of the clout that i (a stupid indian) have and u couldn't have. Either way, have a good day ![image](https://private-user-images.githubusercontent.com/75808182/294695780-353f5377-a053-469c-8d5b-0b5a78c8cb4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU3ODAtMzUzZjUzNzctYTA1My00NjljLThkNWItMGI1YTc4YzhjYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NTJmN2U4NWU3ZjZkZTYwYjEyYTNmY2U4MDdjMzg5ZGQzMTQ1NWFmMjMwODRjNDQwN2YyMmIyMWQ4M2IwODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1qyAlYOj1Abr70I7Cs9QB0qJ_eG959Rrxmr4mXcd9jE) ![image](https://private-user-images.githubusercontent.com/75808182/294695782-43cc83e9-86d2-43cd-a177-36ab0e722cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU3ODItNDNjYzgzZTktODZkMi00M2NkLWExNzctMzZhYjBlNzIyY2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYTI4YjY3YzFkYTg1ODczZGU4MWU4OTI0MDUzMzBjMmI2OTM1OWQ5ZTczMTRkNjgxNGRhZDM0NmIyODUxZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ABu-PIUYOdgkHtQvZZPcV6QZoUTJdG6N9InKiljJvg8) ![image](https://private-user-images.githubusercontent.com/75808182/294695802-088b2d22-a1e8-4468-b542-005dc305cb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU4MDItMDg4YjJkMjItYTFlOC00NDY4LWI1NDItMDA1ZGMzMDVjYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxN2YwMTk2ZTRmYTA4YjJhMzVkZmNjNGQ2NzhhNDE5MmU0N2ZlMTNiMTY0MzE1ZDAwMWM1OTZjNjdjYWZiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X9mGV29GcB4XNttJotCO0TEkE2eIyJYFDlzacb8f_BE) ![image](https://private-user-images.githubusercontent.com/75808182/294695917-2e4ea6a7-156b-4f75-ba85-60371ad67770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU5MTctMmU0ZWE2YTctMTU2Yi00Zjc1LWJhODUtNjAzNzFhZDY3NzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Y2RhMWI0MmQxNWE4MTc1NDlmNDgzMDRjMDQ2M2U0MzU3NGY4ZjRiNDI3OGI2MmEzNGQwODNkMmYyNDAyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2u7ujZodGw9EeUOH5IZ6ZSdLjdMfY-V2jHJp4QQmOPQ) ![image](https://private-user-images.githubusercontent.com/75808182/294695940-4319a8f1-37cb-4dfc-830a-eea0e596d5a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTU5NDAtNDMxOWE4ZjEtMzdjYi00ZGZjLTgzMGEtZWVhMGU1OTZkNWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYTk3ZTdiMDdhMmZiMjZjNWM5N2YyZGMwMDZhODg2OWE2MTc0NWEwNjRmNzI5NDc3OGExYjg2YTU0NjMyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nb1Zw5bp6aWWT38hekx1Jp7i1Eyfj6tUfoYn0pfCvE) ![image](https://private-user-images.githubusercontent.com/75808182/294696043-f3c0cec4-b914-4679-8ed3-80db9ed2bd23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NjM3MTEsIm5iZiI6MTcwNDU2MzQxMSwicGF0aCI6Ii83NTgwODE4Mi8yOTQ2OTYwNDMtZjNjMGNlYzQtYjkxNC00Njc5LThlZDMtODBkYjllZDJiZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE3NTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzM2JhZjg4YjBkMGU4NGJhZmY4OGUwYTZmNGM5OGFhMDMxNWJjZTUyZjdkY2E5Zjc0ZDBmMTE4MGFlZDBmMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OjfHO02phHzZ1BxLYAU9k_XjfoBkHdBTqXCi7y_55uw)


Yes, I am aware of custom Windows ISOs which still doesn't make Windows superior to any other UNIX based OS. Furthermore this "Token Logger" you wrote doesn't even do it's job. Go learn how to make good malware
